### ISSUE TITLE
Brainstorm how to compute payout variance

### ISSUE THREAD

**Issue by Staneesh** [Staneesh/optionator#9]
We don't know if path-dependent total payout variance captures potential portfolio correlations. More research (and future implementation) needed.

**Comment by Nadim-Muhammad** [comment]
https://en.wikipedia.org/wiki/Modern_portfolio_theory

**Comment by Staneesh** [comment]
Can you expand on the above? What is the general idea that follows form MPT exactly?

**Comment by Nadim-Muhammad** [comment]
With my understanding of the topic I think we can choose how to calculate the variance. I think for an algo-trader using variance calculations from MPT is better than the usage of (simple) variance. MPT is just a standard.

**Comment by Staneesh** [comment]
Don't we have just one asset though? Or do you understand options as assets? What is the correlation between a short call and a long put?

**Comment by Nadim-Muhammad** [comment]
Our portfolio consists of options with the common underlying asset. We can call it for this case I understand options as "assets". Payout of those options are different, depending on Time to Expiry, Strike Price etc.. I wouldn't look at correlations as -1/1, rather we can calculate it (because we know the payouts).

**Comment by Staneesh** [comment]
How to calculate such correlation? What option-defining parameters could have an impact? 

An idea - maybe the correlation will be naturally accounted for during Monte Carlo simulation of the underlying?

**Comment by Nadim-Muhammad** [comment]
![image](https://github.com/Staneesh/optionator/assets/128726632/98448cd4-034a-4b19-a16b-1724dea7746a)

We can calculate covariance (instead of correlation - much easier with our data). But portfolio variance from MPT:
![image](https://github.com/Staneesh/optionator/assets/128726632/6a7dca14-464b-413b-a0cd-ff6fd455f8c4)

uses weights. I'm not sure if those weights should be Trade_Volume/Sum_of_Options_In_Portfolio or what.

**Comment by Staneesh** [comment]
I see, could you please ask the lecturer about this idea next time? We could resume this discussion then. I will try to implement a simple path-dependent variance calculator in the meantime.

**Comment by Nadim-Muhammad** [comment]
I'll ask someone to ask on my behalf, because I won't be able to attend last c++ classes due to the railway workers' strike (info: https://www.wkd.com.pl/aktualnosci/3129-informacja-wkd-3-na-temat-sytuacji-strajkowej-na-linii-wkd)

**Comment by Nadim-Muhammad** [comment]
With simulations i think we can just calculate variance in a simple way (without MPT/covariances etc).

**Comment by Staneesh** [comment]
Cool, please check out #17 🚀
